### ISSUE TITLE
using LineaRE as decoder

### ISSUE THREAD

**Issue by felipemello1** [pengyanhui/LineaRE#2]
Hi, thanks for the paper and for sharing the code! Great work! I wanted to experiment with using LineaRE as the head of my convolution (GAT/GIN/etc). The embeddings would come from the convolutions and the other 3 vectors would be trainable parameters (W1, W2, b). Do you see any theoretical reason for why this would not work, or would be worse than the LineaRE alone?

Thanks in advance!!

**Comment by pengyanhui** [comment]
Thank you for your interest in our work!
I'm not sure about the structure of your convolutional network. The reason may be that some properties of the relations in KGs require the randomness of the initial embeddings to be obtained, such as two different symmetric relations that require different distributions of the slopes (-1, 1) of the lines to be distinguished. If a convolutional network is used as the pre-training model, it may have some unknowable effects on these distributions.

**Comment by felipemello1** [comment]
Thanks!
