### ISSUE TITLE
你好，想问一下，由于只有FB15k有Sym，inv，composition这样的数据文件，我还想在其他的数据集也进行这样的测试，有公开的代码吗，感谢感谢

### ISSUE THREAD

**Issue by stevenlyf428** [pengyanhui/LineaRE#7]

**Comment by pengyanhui** [comment]
不好意思，前段时间回家了，没上线。
你说的是测试数据集的划分吗？那个只是我自定义的，没什么标准，怕得不到审稿人的认可，所以论文里没写。
这个划分很简单。拿对称关系来说，对于测试三元组（h,r,t），检测训练集中是否存在（t,r,h），如果存在，则把（h,r,t）划分到对称测试集。inv 也同理。com，对于测试三元组（h,r,t），你检测训练集中是否存在（h,r1,e)（e,r2,t)，也就是 h 和 t 之间有没有关系路径，有的话就划分到com。
由于这个代码比较简单，我没保存，你试着写写看。

**Comment by pengyanhui** [comment]
> _No description provided._

不好意思，前段时间回家了，没上线。
你说的是测试数据集的划分吗？那个只是我自定义的，没什么标准，怕得不到审稿人的认可，所以论文里没写。
这个划分很简单。拿对称关系来说，对于测试三元组（h,r,t），检测训练集中是否存在（t,r,h），如果存在，则把（h,r,t）划分到对称测试集。inv 也同理。com，对于测试三元组（h,r,t），你检测训练集中是否存在（h,r1,e)（e,r2,t)，也就是 h 和 t 之间有没有关系路径，有的话就划分到com。
由于这个代码比较简单，我没保存，你试着写写看。

**Comment by stevenlyf428** [comment]
谢谢回复，太感谢了！！！！！

**Comment by pengyanhui** [comment]
> 谢谢回复，太感谢了！！！！！

以后多多交流。

**Comment by CuiJie98** [comment]
代码有了吗 老哥
